import { parseFrontmatter, read, today, walk, write } from './docs-utils.mjs';

const docs = walk('docs', f => f.endsWith('.md'));
const mapRows = [];
const adrRows = [];

for (const file of docs) {
  const content = read(file);
  const fm = parseFrontmatter(content) || {};
  const title = content.match(/^#\s+(.+)$/m)?.[1] || file;
  if (!file.includes('/memory/sessions/') && !file.includes('/memory/archive/')) {
    mapRows.push({ file, type: fm.type || '', status: fm.status || '', context: fm.context_policy || '', title });
  }
  const adr = file.match(/^docs\/adr\/(\d+)-(.+)\.md$/);
  if (adr) adrRows.push({ id: adr[1], status: fm.status || '', title });
}

let index = read('docs/index.md');
const marker = '## Document Map';
const before = index.includes(marker) ? index.slice(0, index.indexOf(marker)) : index + '\n';
let documentMap = `${marker}\n\n| Path | Type | Status | Context policy | Purpose |\n|---|---|---|---|---|\n`;
for (const r of mapRows.sort((a,b)=>a.file.localeCompare(b.file))) {
  documentMap += `| \`${r.file}\` | \`${r.type}\` | \`${r.status}\` | \`${r.context}\` | ${r.title.replace(/^ADR-\d+:\s*/, '')} |\n`;
}

documentMap += `\n## Automation Commands\n\n\`\`\`bash\nnpm run docs:new-session\nnpm run docs:sync\nnpm run docs:guard-size\nnpm run docs:guard-schema\nnpm run docs:guard-links\nnpm run docs:guard-placeholders\nnpm run docs:guard-adr-status\nnpm run docs:guard-task-status\nnpm run docs:audit-frontmatter\nnpm run docs:narrative-check\nnpm run docs:completed-regen\nnpm run docs:refresh\n\`\`\`\n`;
write('docs/index.md', before + documentMap);

let decisions = `---\ntype: decision_index\nstatus: active\npriority: p1\nupdated: ${today()}\ncontext_policy: retrieve_only\nowner: project\n---\n\n# Decision Index\n\n<!-- AUTO-GENERATED by scripts/docs-sync.mjs -->\n\n| ADR | Status | Title |\n|---|---|---|\n`;
for (const r of adrRows.sort((a,b)=>a.id.localeCompare(b.id))) decisions += `| \`${r.id}\` | ${r.status} | ${r.title} |\n`;
write('docs/decisions.md', decisions);

console.log(`docs synced: ${mapRows.length} docs, ${adrRows.length} ADRs`);
